/******************************************
Treehouse FSJS Techdegree:
project 1 - A Random Quote Generator
******************************************/

// Study guide for this project - https://drive.google.com/file/d/1s5grutGuQFwJcQP8bFwEI69Q8FCkGdDk/view?usp=sharing

var randomNumber;
var timeOut = window.setInterval(printQuote, 20000);

/*** 
 Create the array of quote objects and name it `quotes`.
 Add at least five quote objects to the `quotes` array.
 Give each quote object a `quote` and `source` property.
 Add the `citation` property to at least one object in the array.
 Add the `year` property to at least one object in the array.
 Use console.log() to log your array of quotes to the console.
 ***/


var quotes = [
{
  quote: "Strength does not come from winning. Your struggles develop your strengths. When you go through hardships and decide not to surrender, that is strength.",
  source: "Arnold Schwarzenegger",
  citation: "From a 1982 interview with Boston Globe journalist Marian Christy.",
  year: "1982"
},
{
  quote: "When you're young, you look at television and think, There's a conspiracy. The networks have conspired to dumb us down. But when you get a little older, you realize that's not true. The networks are in business to give people exactly what they want. That's a far more depressing thought. Conspiracy is optimistic! You can shoot the bastards! We can have a revolution! But the networks are really in business to give people what they want. It's the truth.",
  source: "Steve Jobs",
  citation: "Interview in WIRED magazine",
  year: "1996"
},
{
  quote: "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  source: "Mahatma Ghandi",
  citation: "pre-dating Gandhi, attributed to Isidore of Seville",
  year: "c. 560 – 636"
},
{
  quote: "This above all: to thine own self be true.",
  source: "William Shakespeare" 
},
{
  quote: "A journey of a thousand leagues begins beneath one’s feet.",
  source: "Lao Tzu"
},
];

/***
  Create the `getRandomQuote` function to:
   - Create a variable to store a random number 
   - Cse the random number to `return` a random quote object from the `quotes` array.
***/

function getRandomQuote() {
  var randomNumber = Math.floor(Math.random() * quotes.length);
  return quotes[randomNumber];
};


//Gets random number from 0 - 255
function randomRGB(){
var rgb = Math.floor(Math.random() * 256 );
return rgb;
}
//Changes Background color to random rgb value generated by random RGB
function changeBG() {
  var rgbValue = 'rgb(' + randomRGB() + 
  ',' + randomRGB() + ',' + randomRGB() + ')';
  document.body.style.backgroundColor = rgbValue;
}

function changeButtonBg() {
  var buttonBGColor = document.getElementById('loadQuote')
  var rgbValue = 'rgb(' + randomRGB() +
    ',' + randomRGB() + ',' + randomRGB() + ')';
  buttonBGColor.style.backgroundColor = rgbValue;
}

function printQuote() {
  var ranQuote = getRandomQuote();
  var htmlString = '';
  var quoteBox = document.getElementById('quote-box');

  htmlString += '<p class="quote">' + ranQuote.quote +  '</p> <p class="source">' + ranQuote.source + '</p>';
  if (ranQuote['citation'] != undefined) {
   htmlString += '<span class="citation">' + ranQuote.citation + '</span>';
  }
  if (ranQuote['year'] != undefined) {
    htmlString += '<span class="year">' + ranQuote.year + '</span>';
  }
  quoteBox.innerHTML = htmlString;
  changeBG();
  changeButtonBg();
};


//listens for click on load another quote button
document.getElementById('loadQuote').addEventListener("click", printQuote, false);


// Remember to delete the comments that came with this file, and replace them with your own code comments.